ToDoList/ToDoList/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import Home
from list.views import ToDoListView

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('list/', include('list.urls')),
    #Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls'))
]

ToDoList/list/urls.py
from django.urls import path
from .views import ToDoListView, CreateTaskView, DeleteTaskView, UpdateTaskView, IndividualTaskView, CreateSubTaskView, UpdateSubTaskView, DeleteSubTaskView

urlpatterns = [
    path('<str:user>/', ToDoListView.as_view(), name="lista"),
    path('<str:user>/create', CreateTaskView.as_view(), name="create"),
    path('<str:user>/<int:pk>', IndividualTaskView.as_view(), name="detail"),
    path('<str:user>/<int:pk>/update', UpdateTaskView.as_view(), name="update"),
    path('<str:user>/<int:pk>/delete', DeleteTaskView.as_view(), name="delete"),
    path('<str:user>/<int:task_pk>/create-subtask', CreateSubTaskView.as_view(), name="sub-create"),
    path('<str:user>/<int:task_pk>/update-subtask/<int:pk>', UpdateSubTaskView.as_view(), name="sub-update"),
    path('<str:user>/<int:task_pk>/delete-subtask/<int:pk>', DeleteSubTaskView.as_view(), name="sub-delete")
]

ToDoList/registration/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

ToDoList/core/models.py
from django.db import models

# Create your models here.

ToDoList/list/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User

# Create your models here.

class List(models.Model):
    title = models.CharField(blank=False, null=False, max_length=200)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title
    
class Task(models.Model):
    title = models.CharField(blank=False, null=False, max_length=200)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(List, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title
    
class SubTask(models.Model):
    title = models.CharField(blank=False, null=False, max_length=200)
    is_completed = models.BooleanField(default=False)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title
    
@receiver(post_save, sender=User)
def ensure_assigned_list(sender, instance, **kwargs):
    if kwargs.get('created', False):
        List.objects.get_or_create(user=instance, title="lista de {}".format(instance))

@receiver(post_save, sender=SubTask)
def complete_task_if_all_subtasks_completed(sender, instance, **kwargs):
    subtasks = SubTask.objects.filter(task_id=instance.task_id)
    if all(subtask.is_completed for subtask in subtasks):
        task = Task.objects.get(id=instance.task_id)
        if not task.is_completed:
            task.is_completed = True
            task.save()

@receiver(post_save, sender=Task)
def complete_subtasks_if_task_completed(sender, instance, **kwargs):
    if instance.is_completed:
        subtasks = SubTask.objects.filter(task_id=instance.id)
        for subtask in subtasks:
            if not subtask.is_completed:
                subtask.is_completed = True
                subtask.save()

ToDoList/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class Home(TemplateView):
    template_name = "core/home.html"

ToDoList/list/views.py
from typing import Any
from django.db import transaction
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic import CreateView, DeleteView, UpdateView, DetailView
from .models import List, Task, SubTask

# Create your views here.

class LoginRequiredMixin(object):
    """Mixing to avoid landing on other users list pages"""

    def dispatch(self, request, *args, **kwargs):
        if request.user.get_username() not in request.path:
            return redirect(reverse_lazy('home'))
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)

class ToDoListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'list/list.html'

    def get_queryset(self):
        user_list = List.objects.filter(title=f"lista de {self.request.user.get_username()}").first()
        return super().get_queryset().filter(list_id=user_list.id)
    
class IndividualTaskView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'list/detail.html'

    def get_success_url(self):
        return reverse_lazy('lista', args=[self.request.user.get_username()])
    
class CreateTaskView(LoginRequiredMixin, CreateView):
    model = Task
    fields = ["title"]
    
    def get_success_url(self):
        return reverse_lazy('lista', args=[self.request.user.get_username()])

    def form_valid(self, form):
        form.instance.list = List.objects.get(title="lista de {}".format(self.request.user.get_username()))
        return super().form_valid(form)
    
class UpdateTaskView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]
    template_name_suffix = "_update_form"

    @transaction.atomic
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('lista', args=[self.request.user.get_username()])
    
class DeleteTaskView(LoginRequiredMixin, DeleteView):
    model = Task
    
    def get_success_url(self):
        return reverse_lazy('lista', args=[self.request.user.get_username()])
    
class CreateSubTaskView(LoginRequiredMixin, CreateView):
    model = SubTask
    fields = ["title"]
    
    def get_success_url(self):
        return reverse_lazy('detail', args=[self.request.user.get_username(), self.kwargs['task_pk']])

    def form_valid(self, form):
        form.instance.task = Task.objects.get(id=self.kwargs['task_pk'])
        return super().form_valid(form)
    
class UpdateSubTaskView(LoginRequiredMixin, UpdateView):
    model = SubTask
    fields = ["is_completed"]
    template_name_suffix = "_update_form"

    @transaction.atomic
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('detail', args=[self.request.user.get_username(), self.object.task_id])
    
class DeleteSubTaskView(LoginRequiredMixin, DeleteView):
    model = SubTask
    
    def get_success_url(self):
        return reverse_lazy('detail', args=[self.request.user.get_username(), self.object.task_id])
    

ToDoList/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <!-- Fuentes -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Estilos -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'core/css/main.css' %}" rel="stylesheet">
  </head>
  <body>
    <body>
      <!-- Navegación -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">To Do List</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ned" aria-controls="ned" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="ned">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Inicio</a>
              </li>
            </ul>
            <ul class="navbar-nav">
              {% if not request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Acceder             
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'signup' %}">Registro             
                  </a>
                </li>
              {% else %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'lista' request.user.get_username %}">Lista                   
                </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Salir                   
                  </a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <!-- Contenido -->
      {% block content %}{% endblock %}
      <!-- Javascript -->
      <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'core/js/main.js' %}"></script>
  </body>
</html>

ToDoList/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
<div class="container">
  <div style="padding-top:50px; text-align:center;">
    <h1>Your To Do list</h1>
    <p class="lead">Create, Update and Delete tasks from task list</p>
  </div>
</div>
{% endblock %}

ToDoList/list/templates/list/detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Tarea{% endblock %}
{% block content %}

<h1>Title: {{ task.title }}</h1> <a class="nav-link" href="{% url 'update' request.user.get_username task.pk %}">Actualizar estado </a></p>
{% for subtask in task.subtask_set.all %}
{% if subtask.task_id == task.id %}
<p>- {{subtask.title}} {% if subtask.is_completed == True %}✓{% endif %}<a class="nav-link" href="{% url 'sub-update' request.user.get_username task.pk subtask.pk %}">Modificar sub-tarea</a>
    <a class="nav-link" href="{% url 'sub-delete' request.user.get_username task.pk subtask.pk %}">Borrar sub-tarea </a></p>
{% endif %}
{% endfor %}

<a class="nav-link" href="{% url 'sub-create' request.user.get_username task.id %}">Crear sub-tarea

{% endblock %}

ToDoList/list/templates/list/list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Lista de tareas{% endblock %}
{% block content %}

{% for task in task_list %}
<h2>{{ task }} {% if task.is_completed == True %}✓{% endif %}</h2>
{% for subtask in task.subtask_set.all %}
{% if subtask.task_id == task.id %}
<p> -  {{subtask.title}} {% if subtask.is_completed == True %}✓{% endif %}</p>
{% endif %}
{% endfor %}
<a class="nav-link" href="{% url 'detail' request.user.get_username task.pk %}">Modificar tarea</a>
<a class="nav-link" href="{% url 'delete' request.user.get_username task.pk %}">Borrar tarea </a>
{% endfor %}

<a class="nav-link" href="{% url 'create' request.user.get_username %}">Crear tarea

</a>
{% endblock %}

ToDoList/list/templates/list/subtask_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar{% endblock %}
{% block content %}

<form method="post">{% csrf_token %}
    <p>Seguro que deseas borrar la tarea "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirmar">
</form>

{% endblock %}

ToDoList/list/templates/list/subtask_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Agregar tarea{% endblock %}
{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

{% endblock %}

ToDoList/list/templates/list/subtask_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Actualizar tarea{% endblock %}
{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}

ToDoList/list/templates/list/task_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar{% endblock %}
{% block content %}

<form method="post">{% csrf_token %}
    <p>Seguro que deseas borrar la tarea "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirmar">
</form>

{% endblock %}

ToDoList/list/templates/list/task_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Agregar tarea{% endblock %}
{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

{% endblock %}

ToDoList/list/templates/list/task_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Actualizar tarea{% endblock %}
{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}